# Emotion sentiment classification
emotion_sentiment = {
    "admiration": "positive",
    "amusement": "positive",
    "anger": "negative",
    "annoyance": "negative",
    "approval": "positive",
    "caring": "positive",
    "confusion": "neutral",
    "curiosity": "neutral",
    "lust": "negative",
    "disappointment": "negative",
    "disapproval": "negative",
    "disgust": "negative",
    "embarrassment": "negative",
    "excitement": "positive",
    "fear": "negative",
    "gratitude": "positive",
    "grief": "negative",
    "joy": "positive",
    "love": "positive",
    "nervousness": "negative",
    "optimism": "positive",
    "pride": "positive",
    "realization": "neutral",
    "relief": "positive",
    "remorse": "negative",
    "sadness": "negative",
    "surprise": "neutral",
    "neutral": "neutral"
}